version: "3"

services:

  server:
    container_name: server
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
